language: python
cache: pip
python:
    - "3.6"
    - "3.7"

before_script:
  - pip install -r requirements.txt

script:
  - pytest -v ./test_smoke.py

notifications:
  email:
    on_success: never
    on_failure: always