version: "3"

services:
  mpyk:
    build:
      context: src
      dockerfile: Dockerfile
    container_name: mpyk
    restart: unless-stopped
    env_file:
      - src/b2_prod.env
    volumes:
      - "/mnt/storage/mpyk/csv:/mpyk/csv"
      - "/mnt/storage/mpyk/zip:/mpyk/zip"
    command: [ "python", "./mpyk_collect.py", "15", "/mpyk/csv", "/mpyk/zip" ]